"""Base dataclasses for session entries"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['now_iso', 'gen_id', 'SessionHeader', 'MessageEntry', 'CompactionEntry', 'ModelChangeEntry',
           'ThinkingLevelChangeEntry', 'CustomEntry', 'LabelEntry']

# %% ../nbs/00_core.ipynb #984f325d
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional, Union, List, Dict, Any

# %% ../nbs/00_core.ipynb #23ed9be2
def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()

def gen_id() -> str:
    import uuid
    return uuid.uuid4().hex[:8]

# %% ../nbs/00_core.ipynb #8bf47b19
@dataclass
class SessionHeader:
    type: str = 'session'
    version: int = 1
    id: str = field(default_factory=gen_id)
    timestamp: str = field(default_factory=now_iso)
    cwd: str = ''
    parentSession: Optional[str] = None

# %% ../nbs/00_core.ipynb #4eadbad3
@dataclass
class MessageEntry:
    type: str = 'message'
    id: str = field(default_factory=gen_id)
    parentId: Optional[str] = None
    timestamp: str = field(default_factory=now_iso)
    role: str = ''
    content: Union[str, List[Dict[str, Any]]] = ''

# %% ../nbs/00_core.ipynb #5bbed7eb
@dataclass
class CompactionEntry:
    type: str = 'compaction'
    id: str = field(default_factory=gen_id)
    parentId: Optional[str] = None
    timestamp: str = field(default_factory=now_iso)
    summary: str = ''
    firstKeptEntryId: str = ''

# %% ../nbs/00_core.ipynb #97b8c4fd
@dataclass
class ModelChangeEntry:
    type: str = 'model_change'
    id: str = field(default_factory=gen_id)
    parentId: Optional[str] = None
    timestamp: str = field(default_factory=now_iso)
    provider: str = ''
    modelId: str = ''

# %% ../nbs/00_core.ipynb #5d3e0177
@dataclass
class ThinkingLevelChangeEntry:
    type: str = 'thinking_level_change'
    id: str = field(default_factory=gen_id)
    parentId: Optional[str] = None
    timestamp: str = field(default_factory=now_iso)
    thinkingLevel: str = 'off'

# %% ../nbs/00_core.ipynb #68f99df1
@dataclass
class CustomEntry:
    type: str = 'custom'
    id: str = field(default_factory=gen_id)
    parentId: Optional[str] = None
    timestamp: str = field(default_factory=now_iso)
    customType: str = ''
    data: Any = None

# %% ../nbs/00_core.ipynb #872c92b8
@dataclass
class LabelEntry:
    type: str = 'label'
    id: str = field(default_factory=gen_id)
    parentId: Optional[str] = None
    timestamp: str = field(default_factory=now_iso)
    targetId: str = ''
    label: Optional[str] = None
