"""Unified wrapper for session entries"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_session.ipynb.

# %% auto #0
__all__ = ['SessionEntry']

# %% ../nbs/01_session.ipynb #d2e37977
from dataclasses import asdict
from typing import Optional, Union, List
from .core import ( gen_id,    MessageEntry, CompactionEntry, ModelChangeEntry,    ThinkingLevelChangeEntry, CustomEntry, LabelEntry)

# %% ../nbs/01_session.ipynb #bc756af0
class SessionEntry:
    def __init__(self, entry):
        self._entry = entry

    @property
    def id(self) -> str:
        return self._entry.id

    @property
    def parentId(self) -> Optional[str]:
        return self._entry.parentId

    @property
    def type(self) -> str:
        return self._entry.type

    @property
    def timestamp(self) -> str:
        return self._entry.timestamp

    def to_dict(self) -> dict:
        return asdict(self._entry)

    @classmethod
    def from_dict(cls, d: dict):
        t = d.get('type')
        if t == 'message':
            return cls(MessageEntry(**d))
        if t == 'compaction':
            return cls(CompactionEntry(**d))
        if t == 'model_change':
            return cls(ModelChangeEntry(**d))
        if t == 'thinking_level_change':
            return cls(ThinkingLevelChangeEntry(**d))
        if t == 'custom':
            return cls(CustomEntry(**d))
        if t == 'label':
            return cls(LabelEntry(**d))
        raise ValueError(f'unknown type: {t}')

    def __getattr__(self, name):
        return getattr(self._entry, name)

