# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06a_agent.events.ipynb.

# %% auto #0
__all__ = ['AgentEvent', 'AgentStartEvent', 'AgentEndEvent', 'TurnStartEvent', 'TurnEndEvent', 'MessageStartEvent',
           'MessageUpdateEvent', 'MessageEndEvent', 'ToolExecStartEvent', 'ToolExecUpdateEvent', 'ToolExecEndEvent']

# %% ../../nbs/06a_agent.events.ipynb #bd9058ec
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Literal, Optional

@dataclass
class AgentEvent:
    """Base class for all agent events."""
    type: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert event to dictionary."""
        return asdict(self)
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AgentEvent":
        """Create event from dictionary. Subclasses override."""
        event_type = data.get("type")
        # Dispatch to correct subclass
        event_map = {
            "agent_start": AgentStartEvent,
            "agent_end": AgentEndEvent,
            "turn_start": TurnStartEvent,
            "turn_end": TurnEndEvent,
            "message_start": MessageStartEvent,
            "message_update": MessageUpdateEvent,
            "message_end": MessageEndEvent,
            "tool_execution_start": ToolExecStartEvent,
            "tool_execution_update": ToolExecUpdateEvent,
            "tool_execution_end": ToolExecEndEvent,
        }
        event_cls = event_map.get(event_type, cls)
        return event_cls(**data)

# %% ../../nbs/06a_agent.events.ipynb #cc371506
@dataclass
class AgentStartEvent(AgentEvent):
    type: Literal["agent_start"] = "agent_start"

@dataclass
class AgentEndEvent(AgentEvent):
    type: Literal["agent_end"] = "agent_end"
    messages: List[Any] = field(default_factory=list)

@dataclass
class TurnStartEvent(AgentEvent):
    type: Literal["turn_start"] = "turn_start"
    turnIndex: int = 0

@dataclass
class TurnEndEvent(AgentEvent):
    type: Literal["turn_end"] = "turn_end"
    turnIndex: int = 0
    message: Optional[Any] = None
    toolResults: List[Any] = field(default_factory=list)

# %% ../../nbs/06a_agent.events.ipynb #4c390973
@dataclass
class MessageStartEvent(AgentEvent):
    type: Literal["message_start"] = "message_start"
    message: Optional[Any] = None

@dataclass
class MessageUpdateEvent(AgentEvent):
    type: Literal["message_update"] = "message_update"
    message: Optional[Any] = None
    delta: Optional[Any] = None

@dataclass
class MessageEndEvent(AgentEvent):
    type: Literal["message_end"] = "message_end"
    message: Optional[Any] = None

# %% ../../nbs/06a_agent.events.ipynb #1a25b906
@dataclass
class ToolExecStartEvent(AgentEvent):
    type: Literal["tool_execution_start"] = "tool_execution_start"
    toolCallId: str = ""
    toolName: str = ""
    args: Dict[str, Any] = field(default_factory=dict)

@dataclass
class ToolExecUpdateEvent(AgentEvent):
    type: Literal["tool_execution_update"] = "tool_execution_update"
    toolCallId: str = ""
    toolName: str = ""
    args: Dict[str, Any] = field(default_factory=dict)
    partialResult: Optional[Any] = None

@dataclass
class ToolExecEndEvent(AgentEvent):
    type: Literal["tool_execution_end"] = "tool_execution_end"
    toolCallId: str = ""
    toolName: str = ""
    result: Optional[Any] = None
    isError: bool = False
