# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/06b_agent.hookspec.ipynb.

# %% auto #0
__all__ = ['hookspec', 'hookimpl', 'AgentHookSpec']

# %% ../../nbs/06b_agent.hookspec.ipynb #0679dbe5
import pluggy

hookspec = pluggy.HookspecMarker("memexcode.agent")
hookimpl = pluggy.HookimplMarker("memexcode.agent")

# %% ../../nbs/06b_agent.hookspec.ipynb #6599619f
class AgentHookSpec:
    """Hook specifications for agent lifecycle events."""
    
    @hookspec(firstresult=True)
    async def before_tool_call(self, tool_name: str, tool_id: str, 
                               args: dict, context, signal):
        """Called before executing a tool. Return dict with block=True to prevent execution."""
        ...
    
    @hookspec(firstresult=True)
    async def after_tool_call(self, tool_name: str, tool_id: str,
                              args: dict, result, is_error: bool, 
                              context, signal):
        """Called after tool execution. Return dict to override result."""
        ...
    
    @hookspec(firstresult=True)
    async def transform_context(self, messages: list, signal) -> list:
        """Transform messages before sending to LLM. Return modified list."""
        ...
    
    @hookspec(firstresult=True)
    async def should_stop_after_turn(self, message, tool_results, 
                                     context, new_messages) -> bool:
        """Return True to stop agent loop after current turn."""
        ...
    
    @hookspec
    async def on_payload(self, payload: dict):
        """Called with LLM request payload (fire-and-forget)."""
        ...
    
    @hookspec
    async def on_response(self, response):
        """Called with raw LLM response (fire-and-forget)."""
        ...
    
    @hookspec
    async def on_turn_start(self, turn_index: int):
        """Called at start of each turn (fire-and-forget)."""
        ...
    
    @hookspec
    async def on_turn_end(self, turn_index: int, message, tool_results):
        """Called at end of each turn (fire-and-forget)."""
        ...
